---
- name: gengerate configuration
  hosts: localhost
  vars: 
    model: cisco_nexus
    module: snmp
    port: 22
    username: "test"
    password: "test"
    command_interval: 0.5
    stdjudge: "Y/N"
    stdconfirm: "Y"

  vars_files:
    - "vars/{{ model }}/{{ module }}.yml"

  tasks:
    - name: generate configuration
      template:
        src: "templates/{{ model }}/{{ module }}.j2"
        dest: "config/{{ item.hostname }}.txt"
      with_items:
        - { hostname: 'cisco_nexus'}

    - name: config device
      ssh_command:
        port: "{{ port }}"
        username: "{{ username }}"
        password: "{{ password }}"
        address: "{{ item.mgtip }}"
        command_interval: "{{ command_interval }}"
        stdjudge: "Y/N"
        stdconfirm: "Y"
        command: ''
        configfile: "config/{{ item.hostname }}.txt"
      with_items:
        - { hostname: 'cisco_nexus', mgtip: '1.1.1.1' }

