---
- name: gengerate configuration
  hosts: localhost
  vars: 
    model: h3c_v7
    module: general
    port: 22
    username: "root"
    password: "BZMmk9r8LpfMTlgl"
    command_interval: 0.5
    vendor: GENERAL
    stdjudge: "Y/N"
    stdconfirm: "Y"

  vars_files:
    - "vars/{{ model }}/{{ module }}.yml"

  tasks:
    - name: generate configuration
      template:
        src: "templates/{{ model }}/{{ module }}.j2"
        dest: "config/{{ item.hostname }}.txt"
      with_items:
        - { hostname: 'h3c-test1'}

    - name: config device
      ssh_command:
        port: "{{ port }}"
        username: "{{ username }}"
        password: "{{ password }}"
        address: "{{ item.mgtip }}"
        command_interval: "{{ command_interval }}"
        stdjudge: "Y/N"
        stdconfirm: "Y"
        command: ''
        configfile: "config/{{ item.hostname }}.txt"
      with_items:
        - { hostname: 'h3c-test1', mgtip: '119.28.225.12' }

